@startuml


React -> ResourceComponent: componentWillMount()
activate ResourceComponent
ResourceComponent -> ClientSling: subscribe(this.getPath(), this, {deph: this.getDepth()})
ClientSling -> Server : ajax
activate Server
ResourceComponent -> ResourceComponent: setState({state: STATE.LOADING})
activate ResourceComponent
ResourceComponent -> ResourceComponent: renderLoading()
deactivate ResourceComponent
ResourceComponent --> React
deactivate ResourceComponent


Server --> ClientSling: resource
deactivate Server

ClientSling -> ResourceComponent: changedResource(path: resource)
activate ResourceComponent
ResourceComponent -> ResourceComponent: setState({state: STATE.LOADED})
activate ResourceComponent
ResourceComponent -> ResourceComponent: renderBody()

deactivate ResourceComponent
ResourceComponent --> ClientSling
deactivate ResourceComponent

@enduml